name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.3' # Change to your Go version
    
    - name: Get dependencies
      run: go mod download

    - name: Build Go code
      run: go build -o TestGoLambda

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name Test-GO --zip-file fileb://TestGoLambda.zip
      env:
        MSG: ${{ secrets.YOUR_SECRET_MSG }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
